from flask import Flask, Response
from picamera2 import Picamera2
import cv2

app = Flask(__name__)

# Initialize the camera
picam = Picamera2()
# Configure for a lower resolution to keep the stream snappy
config = picam.create_preview_configuration(main={"format": 'XRGB8888', "size": (640, 480)})
picam.configure(config)
picam.start()

def generate_frames():
    while True:
        # Capture a single frame as a numpy array
        frame = picam.capture_array()
        
        # Convert the frame to JPEG format
        ret, buffer = cv2.imencode('.jpg', frame)
        frame_bytes = buffer.tobytes()
        
        # Concatenate frame one by one and show result
        yield (b'--frame\r\n'
               b'Content-Type: image/jpeg\r\n\r\n' + frame_bytes + b'\r\n')

@app.route('/video_feed')
def video_feed():
    # Returns the response generated by the generator function
    return Response(generate_frames(), 
                    mimetype='multipart/x-mixed-replace; boundary=frame')

@app.route('/')
def index():
    # A tiny bit of HTML to display the stream
    return '<html><body><h1>Film Digitizer Live Feed</h1><img src="/video_feed"></body></html>'

if __name__ == '__main__':
    # '0.0.0.0' makes it accessible to other devices on your network
    app.run(host='0.0.0.0', port=5000)
